name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Acción de Terraform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}

      - name: Set subscription
        run: az account set --subscription df2de2c2-02df-4934-a701-2ef152bc4372

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: ./infra

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: ./infra

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
        working-directory: ./infra